### ISSUE TITLE
[BUG]: `next lint` doesn't work with staged files

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/website#140]
## What's the Concern

When running the pre-commit hooks on staged files, `next run` fails stating it can't find the `pages` directory (even though it exits). Screenshots attached for further context:

![image](https://user-images.githubusercontent.com/31373860/158426869-f4d5e1dc-9e42-47cf-a003-1cac3807355c.png)
![image](https://user-images.githubusercontent.com/31373860/158426909-ba56d53f-08a9-4336-bf0d-0d5251776339.png)

A possible solution to the issue could be provided in the documentations itself - https://nextjs.org/docs/basic-features/eslint#lint-staged. There's also a discussion with a similar report - https://github.com/vercel/next.js/discussions/30841

cc @DevanshBajaj who identified the issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarmos-san** [comment]
cc @DevanshBajaj who identified the issue.

**Comment by Jarmos-san** [comment]
So, I tried recreating this issue on my local machine & was unsuccessful. I attached a screenshot below for further reference.

![image](https://user-images.githubusercontent.com/31373860/158550213-6a90ca6e-cfa1-4acd-903c-57b52134a84d.png)

This issue requires further investigation & attention so if you're facing similar concerns please help us fix it soon. The [`issue-140`](https://github.com/developersIndia/website/tree/issue-140) branch is used to track & fix this bug.

**Comment by rohantejeswar** [comment]
Doing a little research on it, [`next lint`](https://nextjs.org/docs/basic-features/eslint#linting-custom-directories-and-files) by default applies to `pages/`, `components/`, and `lib/`. To solve this issue, the solution would be to let `next lint` to ignore the `pages/` directory but no eslint rules are working while husky's pre-commit hook is running.

This issue can be verified if you add an eslint rule to `eslintrc.js` and make changes in a file which deliberately breaks the rule. While `npm run lint` will catch this issue but the pre-commit hook does not. Could be a problem with next lint itself.

Running `eslint` instead of `next lint` in the pre-commit hook solves this issue.

**Comment by rohantejeswar** [comment]
The above diagnosis could be a reason for the issue in #108

**Comment by Jarmos-san** [comment]
@rohantejeswar makes sense! The CI/CD pipeline as it stands right now is broken af. I moved #108 to the "next" milestone for now because the priority right now is to get the pipeline's deployment feature working as expected.

And as usual, contributions are welcome so please feel free to take a look at it (or reach out to me on Discord for more info).
